version: '3'

services:
  pg:
    image: postgres:10.11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - pg-storage:/var/lib/postgresql/data/
      - ../pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql

  pgr:
    image: postgrest/postgrest
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/postgres
      - PGRST_DB_SCHEMA=datafest
      - PGRST_DB_ANON_ROLE=anon
    depends_on:
      - pg

  app:
    build: ../..
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=prod
      - PGUSER=${POSTGRES_USER}
      - PGHOST=pg
      - PGSCHEMA=datafest
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - COOKIE_SECRET=${COOKIE_SECRET}
    command: node index.js

volumes:
  pg-storage: